### ISSUE TITLE
[Suggestion] Replace forEach with for loop

### ISSUE THREAD

**Issue by zerebos** [MahdeenSky/BDPlugins#1]
I would suggest and recommend replacing the `forEach` loop found [here](https://github.com/MahdeenSky/BDPlugins/blob/main/TextReplacer/TextReplacer.plugin.js#L33) with a classic for loop using an index. The performance gain would be small but you'd be surprised how many people are running BetterDiscord on absolute potatoes.

**Comment by MahdeenSky** [comment]
Will do, the plugin is something wack that I hacked together with my limited knowledge of Betterdiscord haha

**Comment by MahdeenSky** [comment]
Fixed with https://github.com/MahdeenSky/BDPlugins/commit/28c9bf81d48c48fdf973d9cf552802bf264cd544

**Comment by zerebos** [comment]
Wow that was fast! If you ever want to learn more about BD feel free to reach out.
