### ISSUE TITLE
Changed replacement settings are only saved temporarily, and are lost upon restarting Discord.

### ISSUE THREAD

**Issue by Otaku-2** [MahdeenSky/BDPlugins#3]
I checked the config file in the plugins folder, and it's just a line saying "TextReplacer": "settings", and does not store any edited replacements.

The plugin file itself *seems* to have functions to update, save, and rebuild the lists, but it does not seem to change anything in either file when pressing the Done button in discord, instead throwing away the user-made list for the default one whenever BD reloads the file.

Apologies if anything I said is inaccurate to how the code works, I know very little of js, and am mostly here to report something that seems unintended.

**Comment by zrodevkaan** [comment]
I pushed a pr that'll fix this plus a settings revamp.

`new BdApi` wasnt saving correctly.

**Comment by Otaku-2** [comment]
Ah, apologies for not noticing it was updated further than the version that was on the Plugin Repo, my bad. This version fixes the issue.
