### ISSUE TITLE
[Error] Settings Panel fails to Load (TypeError: Cannot read properties of undefined (reading 'regexes'))

### ISSUE THREAD

**Issue by GH0STP4WZ** [MahdeenSky/BDPlugins#6]
### Before reporting this issue, I confirm that:
 - [x] I am using the latest version of the addon.
 - [x] The issue is not caused by any other addons.

# Settings panel Fails to load.
Currently, the plugin fails to load its settings panel. A log with the recorded error has been provided below:
```log
TypeError: Cannot read properties of undefined (reading 'regexes')
    at SettingsPanel (TextReplacer.plugin.js:59:61)
    at ob (30550.01a5781bc8def3f12036.js:1:808076)
    at u (30550.01a5781bc8def3f12036.js:1:863286)
    at sI (30550.01a5781bc8def3f12036.js:1:846302)
    at 30550.01a5781bc8def3f12036.js:1:846168
    at sN (30550.01a5781bc8def3f12036.js:1:846176)
    at sT (30550.01a5781bc8def3f12036.js:1:842927)
    at sx (30550.01a5781bc8def3f12036.js:1:843316)
    at r6 (30550.01a5781bc8def3f12036.js:1:791951)
    at 30550.01a5781bc8def3f12036.js:1:840799
e.<computed> @ 41039.165da6fce4d020686e14.js:1
```
I've also included a screenshot below of the notice that shows when attempting to load the settings panel.
![image](https://github.com/MahdeenSky/BDPlugins/assets/87764384/ac11c624-ad65-438d-b930-92f2bbcad51c)

Other potentially important information include:
> Discord Branch: Development
> - Discord Build: `canary 267408 (e6aa7f6)`
> - Host: `0.0.13 x64`
> - OS: `Linux 64-bit (6.7.2-zen1-1-zen)`
> - ASAR: `OpenAsar Nigtly (4f264d8)`
> - Electron: `v28.1.5`
> - Node: `18.18.2`
> - Chrome: `120.0.6099.216`

**Comment by MahdeenSky** [comment]
Fixed by 5050fb3
