### ISSUE TITLE
Text Replacer does not process \? properly

### ISSUE THREAD

**Issue by SnowboundCabin** [MahdeenSky/BDPlugins#7]
Expected result: `\?` would match the literal character `?` and thus adding a rule with regex `\?` and replacement `!` would turn "Foo?" into "Foo!"
Actual result: Message is still "Foo?"

**Comment by MahdeenSky** [comment]
Could not recreate the bug, as it seems to work correctly, as demonstrated here.
<img width="562" alt="Screenshot 2024-03-27 at 9 06 31 PM" src="https://github.com/MahdeenSky/BDPlugins/assets/49484385/bdad3f7e-fc12-4fe0-800f-9b2a7a7e67d9">

Chat Message Before Being Sent:
<img width="58" alt="Screenshot 2024-03-27 at 9 07 14 PM" src="https://github.com/MahdeenSky/BDPlugins/assets/49484385/e5790d79-d236-4703-917f-179260e8b1a7">

After Sent:
<img width="70" alt="Screenshot 2024-03-27 at 9 07 27 PM" src="https://github.com/MahdeenSky/BDPlugins/assets/49484385/8417673a-9e64-4762-8d1a-c423f8148720">
